server:
  port: 10002
  servlet:
    context-path: /consumer

spring:
  application:
    name: feign-consumer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

feign:
  hystrix:
    enabled: true

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 120
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: '*'

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8888/user
#      prefer-token-info: false
#    client:
#      id: admin
#      client-secret: abc123
#      access-token-uri: http://localhost:8888/oauth/token
#      grant-type: password
#      scope: all
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000