server:
  port: 10002

spring:
  application:
    name: feign-consumer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

feign:
  hystrix:
    enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: '*'