server:
  port: 10005
spring:
  application:
    name: zuul-service
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
    fetch-registry: true
management:
  server:
    port: 20005
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  routes:
    consumer:
      path: /consumer/**
      serviceId: feign-consumer
      stripPrefix: false
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 60000
#zuul:
#  routes:
#    api-b:
#      path: /api-b/**
#      serviceId: service-b
#    api-c:
#      path: /api-c/**
#      serviceId: service-c

#users:
#  ribbon:
#    listOfServers: example.com,google.com

