server:
  port: 10000
  servlet:
    context-path:

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10000/eureka/
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: eurka-server
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0