server:
  port: 10000
  servlet:
    context-path:

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10000/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

spring:
  application:
    name: eurka-server
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0