server:
  port: 10000
  servlet:
    context-path:
management:
  server:
    port: 20000
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10000/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

spring:
#  boot:
#    admin:
#      client:
#        url: http://localhost:1234
  application:
    name: eurka-server
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
  profiles:
    include: manager
