server:
  port: 10001
  servlet:
    context-path:
management:
  server:
    port: 20001
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: provider-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8888/user
#      prefer-token-info: false
#    client:
#      id: admin
#      client-secret: abc123
#      access-token-uri: http://localhost:8888/oauth/token
#      grant-type: password
#      scope: all