server:
  port: 10001
spring:
  application:
    name: provider-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8888/user
